/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'numParticipants' : IDL.Nat,
  'preferredTime' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(BookingSubmission)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'numParticipants' : IDL.Nat,
    'preferredTime' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(BookingSubmission)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };